### PR TITLE
v4 Fixes

### PR DESCRIPTION
**Pull request by maggie0002**
- When a file rename error occurs, it seems to repeat it twice 
= _Fixed_
- When saving a new file, text should be ‘save’ instead of ‘create’. I think this would also be better as just two buttons, ‘Save’ and ‘Close’. I see a change made (22ba897), but I think it overlooked that these are the same labels used for editing files too, and when editing the labels aren't very clear. 
= _Merged buttons into Save and Close. Save acts like the old 'save without close' so you can save progress._ 
- When using the move feature, to expand the list of folders you have to click on the folder picture. Ideally it would expand the folder tree when you click anywhere on the text or folder icon 
= _switched the icon for the + and - icons, which are more familiar as clickable to expand the folder tree_
-  Notification should appear on top of active dialog boxes (I.e, the file successfully saved notification is hidden behind the open dialog)
= _Placed notifications at bottom right of active dialog when not viewing the main window_
-  There is a () after the filenames when in the search feature
= _Added default '/' into the parenthesis for when the file is at the root directory_

Some required language file changes have been merged into seperate i18n pull request

### CODE REVIEW

**Comment by novashdima** [comment]
Hi, @maggie0002.
I saw the problem with dup file rename error and as I understand data.message can be more detailed, but in common case we see the same error, as in php exception.
So remove message from js not the best idea...

**Comment by maggie0002** [comment]
> Hi, @maggie0002.
> I saw the problem with dup file rename error and as I understand data.message can be more detailed, but in common case we see the same error, as in php exception.
> So remove message from js not the best idea...

Good point. Not being a PhP person I would usually log the data.message to the console as it’s more user friendly, but not a thing in php I understand? You think it’s better to have the data.message rather than the i18n. 

Or could change the i18n to something more generic like File rename error: data.message

**Comment by novashdima** [comment]
> Or could change the i18n to something more generic like File rename error: data.message ?

I think the best way is to get error from js, return to php code (-1, 0, 1, 2...) and in php process this code and show corresponding message with i18n

**Comment by maggie0002** [comment]
> > Or could change the i18n to something more generic like File rename error: data.message ?
> 
> I think the best way is to get error (or success) from js, return to php code (-1, 0, 1, 2...) and in php process this code and show corresponding message with i18n

That would be cleaner, although would also entail standardising this approach for all the error messages? 

I could change the message which is currently in this pull request as the i18n to the data.message string, then it's easy enough for @misterunknown to amend and change it as they please. Or could remove that commit from this pull request if you are able to take this one on instead?

**Comment by maggie0002** [comment]
Changed them all to data.message string. Not trying to recreate the wheel, and seems like this change brings all the error messaging control into one place and removes the duplicate message.

**Pull request merged**
