### PR TITLE
LDAP filter + logout button fix

### PR DESCRIPTION
**Pull request by cryol**

### CODE REVIEW

**Comment by misterunknown** [comment]
Thanks for your contribution!

**Comment by misterunknown** [comment]
It would be great if you could provide an example for the user filter in the wiki (https://github.com/misterunknown/ifm/wiki/Authentication).

**Comment by cryol** [comment]
**_please add it yourself, as my english is bad_**

In my case, FreeIPA is used as an LDAP server.
For example, you need to give access to a group of site editors - **web_editors**.

In config "**auth_source**" will look like this:

`'ldap;ipa.example.com;cn=users,cn=accounts,dc=example,dc=com;(&(!(nsAccountLock=TRUE))(memberOf=cn=web_editors,cn=groups,cn=accounts,dc=example,dc=com))'`

`'ldap;<SERVER>;<ROOTDN>;<FILTER>'`

where **_<FILTER>_** consists of two conditions:
  - full group pathname: "**(memberOf=cn=web_editors,cn=groups,cn=accounts,dc=example,dc=com)**"
-   and **(!(nsAccountLock=TRUE))** excludes locked accounts

**Comment by misterunknown** [comment]
> please add it yourself, as my english is bad

Ok, is done. Thanks for the example! I don't usually use ldap, so I'm not familiar with the ldap filter string syntax.

> P.S. I would advise removing trigger_error() as this breaks the script in case of an authorization error instead of notifying the user

That's right, I wanted to fix that a long time ago, but didn't came about to do that. I think the consequent solution is to serve the login form via the JS part (#80). I'll do that when I integrate bootstrap 4, which is in the pipeline, but not ready yet.

Cheers,
Marco

**Pull request merged**
