### PR TITLE
V4.0

### PR DESCRIPTION
**Pull request by misterunknown**
Version 4.0

### CODE REVIEW

**Comment by maggie0002** [comment]
Thanks @misterunknown. I will be sure to give this a shot and see if I can identify any issues. It may be a little while before I can though.

**Comment by maggie0002** [comment]
Hi @misterunknown and @novashdima (I think some of these were your pull requests?)

**A few things that have crept up experimenting with v4:**

- [ ] Why is it v4? Was there a v3? I thought we were on 2.6.3?
- [ ] When clicking ‘rename’, the existing filename should be in the input field
- [ ] A warning if removing/changing the file extension would be helpful
- [ ] When using the move feature, to expand the list of folders you have to click on the folder picture. Ideally it would expand the folder tree when you click anywhere on the text or folder icon

Screenshot 2021-02-02 at 17 31 51

- [ ] When a file rename error occurs, it seems to repeat it twice: 

file-rename

- [ ] The permissions box is editable, yet when you try and make a change in the box it isn’t reflected in the files. This should probably be a read-only box rather than one that can be typed in, assuming it isn’t designed to be a way to control folder or file permissions. 
- [ ] There is a () after the filenames when in the search feature:

() in filename

- [ ] When using the search feature, it doesn’t appear to search for partial names, only full ones. I.e. ‘Newfie.txt’ will be found, but ‘newf’ will not return the file. 
- [ ] Is there a term that would be clearer than ‘file’ to represent the remote upload method next to curl? 
- [ ] After a remote upload the image preview isn’t displaying. Somewhat related issue/question around whether this feature adds enough value: https://github.com/misterunknown/ifm/issues/162:

missing-preview

- [ ] When creating a new file via IFM, it occasionally can’t be downloaded by the download link. I’m struggling to get the exact pattern required to replicate it. The URL appears ok using the api=download etc. Works on some files, but not others. Here is my config setup for the directories, hopefully it can be reproduced:

                "root_dir" => "testfolder/",
                "root_public_url" => “testfolder/“,

- [ ] Downloading zip of the root says ‘cannot parse response’. Perhaps related to the above. 
- [ ] What is "pageLength" => 3? How does this differ to ‘Show entities’ in the interface? When setting page length 3, it isn’t reflected in the show entities. If these two are related, perhaps a note in the config file to suggest page length be multiples of 5 like the ‘Show entities’. 
- [ ] Creating a new file, moving, copying or uploading overwrites without warning. 
- [ ] Appears to be some browser caching going on when changing the pageLength variable. At first it didn’t shorten the page length. Then eventually it did but then only showed one page, and had hidden a lot of the folder contents. Opening in a new private browser returned the correct response.  
- [ ] Sometimes the up option vanishes, think related to the page numbers caching issue mentioned above. 

There are a few things that are either issues, things that might be clearer, or both. In general, I think some of these will simplify the interface in really positive ways, reduce the level of maintenance required code wise and translation requirements, while also being more aligned with what people are familiar with in Windows and Mac:

- [ ] When saving a new file, text should be ‘save’ instead of ‘create’. I think this would also be better as just two buttons, ‘Save’ and ‘Close’.  

create-close

- [ ] When uploading a new file, I don’t think the ability to name it during upload is necessary. Ideally it would just append a number to the end if it already exists, and then uploads with its original name. This will simplify needing to add on file extensions to your new name, will close align to what users have on their current systems, and will still allow renaming once it is uploaded. 
- [ ] When remote uploading, not sure if being able to set a filename is required, it just adds another option and is confusing when it isn’t necessary as it will by default keep the original upload name. If the file being added already exists, it would append the filename with a number. 
- [ ] Archive extract could extract right where it is and then can be moved later by the user if need be. While ./ and . are familiar in the tech community, choosing folders like this for everyday users is confusing. Same process of appending with a number if it already exists. 

I will of course try my best to submit pull requests for what I can. @misterunknown would be good to hear which if any you wouldn't want to action to save time.

**Comment by novashdima** [comment]
@maggie0002 
-  There is a () after the filenames when in the search feature:
There is a folder where the file founded
IFM

**Comment by maggie0002** [comment]
> @maggie0002
> 
> * There is a () after the filenames when in the search feature:
>   These are the folders where the file is found, so empty () - current directory
>   IFM

Thinking of leaving it then? Certainly low low priority, just saying it as I see it.

**Comment by novashdima** [comment]
> Thinking of leaving it then? Certainly low low priority, just saying it as I see it. Maybe a default ‘/‘ ?
I think we need to replace empty backets by message, like a "current directory" or rewrite this form.
Maybe "path/<pattern>" should be better, then "<pattern>(path)" .
So in my example we get:
`test.txt`
`1234/test.txt`

**Comment by maggie0002** [comment]
I have reached the technical limits of what I can take on, some of the remaining more complex stuff I would probably do more harm than good.

**Comment by maggie0002** [comment]
@misterunknown it seems that the things left are enhancements rather than bug fixes 👍. Would it be possible to merge the pull requests and publish a release so we can start using it? It’s already a great improvement. And I could transfer remaining enhancements to separate issues?

**Comment by misterunknown** [comment]
My tests were successful so far (#178). I will merge this branch on the weekend.

**Comment by novashdima** [comment]
> My tests were successful so far (#178). I will merge this branch on the weekend.

About this changes...
How I use IFM:
I have 1 page on 1 domain with links to projects, as example:
static.example.org/project1
static.example.org/project2...
every project (dir) has own auth, ifm config etc and we need to have cookie for /project1 /project2....
project1 has root_dir = /var/www/project1, project2: root_dir = /var/www/project2....
with this changes dirname(/project1/); return "/" for all directories, so auth for us broken.
but with basename($_SERVER['REQUEST_URI']); $cookie_path = "/project1", /project2...

**Comment by misterunknown** [comment]
Hm, ok I understand. I'd rather suggest to make an optional config entry for the `session_name`, instead of using the `root_dir` directly. If you use different configs anyway this shouldn't be too much effort.

I guess different `session_name` are much more clean, than trying to determine the `cookie_path` by the `root_dir`. Let me write another update, to fix your issues.

**Comment by misterunknown** [comment]
Ok, the latest push contains both: configurable `session_name` and a complete `cookie_path`. Apparently the `cookie_path` can be any resource, so we don't have to `dirname()` it. With this fix, your authentication should be fixed even without setting specific `session_names`.

**Pull request merged**
