### PR TITLE
Dockerize!

### PR DESCRIPTION
**Pull request by tuschl-digitalmobil**
I've created a basic docker image for running *ifm* inside a docker container.
There is also an automated build for trying it out at https://hub.docker.com/r/digitalmobil/ifm

There's a lot of room for improvement, like configuring ifm settings via docker env vars or extending the documentation, but for the moment it satisfies my needs.

Let me know if you're interested in merging this or if there are any questions / issues you'd like resolved.

### CODE REVIEW

**Comment by misterunknown** [comment]
Thank you very much for your contribution! I never used docker myself, but know what it is. As far as I know, you can't access the filesystem outside the container, so I guess it serves as a little drop box for files? Anyway, this would be also a nice way for providing a demo.

**Comment by misterunknown** [comment]
By the way: I really like alpine linux ;) So this is especially nice!

**Comment by tuschl-digitalmobil** [comment]
You're very welcome! Thank you, for this nifty file manager. 
I'm a long time and convinced vim user - so you had me with the keybindings ;-) 

Actually, the docker image can do a lot more than simply serve as a demo (while this is of course entirely viable). 
My use case is to employ this image as a companion alongside a couple of other containers for accessing (part of) their filesystems (e.g. a wordpress container).

You are right, that a container cannot access the filesystem outside the container, but you can mount directories (or files) from the host system (or other containers) inside the container when creating it.

This enables us to mount the directories we use to persist wordpress uploads into the wordpress container *and* the ifm container. Which provides a nice way for managing this directory without the need for direct server access.

If you're interested, I could assemble a small example what such a setup looks like - when I find the time ;-)

Anway, thanks for merging this. It's really basic for now, but it will get more sophisticated once I get around to it...

**Comment by misterunknown** [comment]
Ah, I understand. This is amazing. I never had thought of that use case. Sounds pretty neat. I'm pleased to hear that the IFM is so useful to people ;)

Don't hesitate to create a pull request, if you have any updates on the docker stuff.

**Pull request merged**
