### PR TITLE
Sane coding style

### PR DESCRIPTION
**Pull request by misterunknown**

### CODE REVIEW

**Comment by maggie0002** [comment]
You think this is about ready to go? I’m thinking of launching with this branch so I don’t have to merge major changes post-launch.

**Comment by misterunknown** [comment]
I just pushed some more commits. Did you test this branch already? I'm not really sure if everything works here. It's been a long time, since I started to write this, and I'm a bit unsure if I should merge it yet.

**Comment by misterunknown** [comment]
Ok, I'll merge this after I merged the other pull request vom @novashdima. Like I said, hopefully next week.

**Comment by maggie0002** [comment]
> Ok, I'll merge this after I merged the other pull request vom @novashdima. Like I said, hopefully next week.

I haven’t had a chance to test. Will give it a run through next week when it’s merged and report back any issues. 

Thanks for all your work on this project.

**Comment by misterunknown** [comment]
@maggie0002 I finally merged this branch to the new branch v4.0, and released an release candidate https://github.com/misterunknown/ifm/releases/tag/v4.0

I merge this into master as fast as possible, I'm not quite sure, if everything works fine.

**Pull request closed without merging**
