### PR TITLE
2.6.1

### PR DESCRIPTION
**Pull request by cryol**
Greetings.
I got a little crazy here.
The entire list of changes is available [here](https://github.com/cryol/ifm/commits/2.6.1).

The main differences:
  - Bootstrap 4
  - Dependencies can be inside or loaded from the CDN.

If there is a merge, then replace the path in the **13th** line of `compiler.php`.

Sincerely, Anton Baranov.

### CODE REVIEW

**Comment by misterunknown** [comment]
Hi! This looks *really* good. I just tried this version in my personal "ifm workspace" and I'm really impressed! So, thank you for this great effort, I'll merge this definitely.

At first sight, two little things need further adjustment, though. First, I noticed that no columns get hidden on mobile devices - apparently the `.hidden-*` classes were removed in bootstrap 4, in favour of `.d-*-block` respectively `.d-*-none` classes. Second, in the "extract archive" dialog, the input groups look a bit broken. [I guess the semantics for them changed](https://getbootstrap.com/docs/4.0/components/input-group/#checkboxes-and-radios).

I'll do a more comprehensive test today, but I guess this can be merged soon.

Thanks again for your work, I really appreciate it!

**Comment by cryol** [comment]
> Second, in the "extract archive" dialog,
Missed this dialog. Fixed.

> First, I noticed that no columns get hidden on mobile devices...
Mobile view seems to be better. But something is wrong.

**Comment by misterunknown** [comment]
Thanks for the fixes. I myself fixed the mobile view and created a PR.

Then only remaining error is that some icons aren't viewed. I just investigate this issue.

**Comment by misterunknown** [comment]
Ok, I found the problem and commited a fix.

**Comment by misterunknown** [comment]
Thanks again for this great work! I'm really glad that the IFM uses now bootstrap 4.

**Pull request merged**
