### PR TITLE
Docker - add config env vars

### PR DESCRIPTION
**Pull request by tuschl-digitalmobil**
I've added support for configuring *ifm* via docker env vars.

The configuration is applied by the startup script on the fly, which enables tweaking / changing the configuration for every run. 

The default values should match those in the IFM script.

### CODE REVIEW

**Comment by misterunknown** [comment]
Thanks for the update. As I see, you directly modify the default configuration within the PHP script. Despite this is possible, I'd rather use the environment variables in the script directly. I guess these docker environment variables are accessible via PHP's `$_ENV` array? If so, this would be a lot more suitable.

**Comment by tuschl-digitalmobil** [comment]
My idea, as with any other dockerization I do, was to be as little invasive into the application itself as possible. This is not uncommon practice. After all, people should still be able to use the app without docker, without adjustments. 

Another thing I'm not sure about, is whether the env vars are preserved by apache - very possible, but it could also clean out the environment - I've just never looked into this. 

If it does preserve and you prefer adopting the env vars directly, keep in mind that for docker the default values are set in the Dockerfile, so you would need another place to provide the defaults for non-docker operation.

**Comment by misterunknown** [comment]
> My idea, as with any other dockerization I do, was to be as little invasive into the application itself as possible. This is not uncommon practice. After all, people should still be able to use the app without docker, without adjustments.

Yes, this is definitely a basic demand of the script – the `ifm.php` should work everywhere, without any adjustment.

> If it does preserve and you prefer adopting the env vars directly, keep in mind that for docker the default values are set in the Dockerfile, so you would need another place to provide the defaults for non-docker operation.

Yes, my idea was to leave the default configuration untouched, but check in the construtor if any relevant environment variables are present, which could override the default config. This would be also a nice way of having a persistent config, even when the IFM script itself gets updated, as pointed out in #62.

**Comment by tuschl-digitalmobil** [comment]
I see, yes tha would of course be an additional value. 

The only thing left that needs to be checked is, whether the env vars arrive at the php script or if they're consumed by apache.

**Comment by misterunknown** [comment]
I merge this anyway, as it works for now. Later, when the IFM recognizes environment variables, this mechanism can be altered.

**Pull request merged**
