### PR TITLE
Assets updates, column autohiding for mobiles and small fixes

### PR DESCRIPTION
**Pull request by novashdima**
@misterunknown check autohiding on mobile plz, on my phone all right
And add translation for new variables "create" and "create_wo_close" for create file & folder modals.

### CODE REVIEW

**Comment by misterunknown** [comment]
Thank you very much for your contribution, I'll take a look asap.

**Comment by misterunknown** [comment]
I just checked this out, and it looks good. One question: Can you prevent that the unfolding mechanism is triggered when I click on a directory to enter it?

**Comment by novashdima** [comment]
> Can you prevent that the unfolding mechanism is triggered when I click on a directory to enter it?
There is no easy way to do this, so I used not so pretty but working dirty hack

**Comment by maggie0002** [comment]
Not thoroughly tested, but as I was opening it up on an iPhone to check another issue, thought I would confirm that it renders and looks ok on iPhone/Safari. 

IMG_14140DA28C53-1

**Comment by misterunknown** [comment]
Ok, unfortunately I'm very busy right now, I think I should find time early next week.

**Comment by misterunknown** [comment]
Hi. I finally merged your changes in #166 and released an release candidate for v4.0. I'm currently very low on time, so I don't really know when I merge this in the master.

I'd really appreciate some feedback for v4.0, so please feel free to report errors or approve it.

**Pull request closed without merging**
